FROM public.ecr.aws/amazonlinux/amazonlinux:2023 AS builder

RUN dnf install -y cmake ninja-build gcc-c++ openssl-devel libcurl-devel zip tar gzip git

WORKDIR /src
COPY . .

RUN mkdir build && cd build && \
    cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=ON && \
    ninja

FROM public.ecr.aws/lambda/provided:al2023

COPY --from=builder /src/build/tests/resources/lambda-test-fun /var/task/bootstrap

RUN chmod +x /var/task/bootstrap

ENTRYPOINT ["/var/task/bootstrap"]
