FROM public.ecr.aws/docker/library/archlinux:latest AS builder

RUN pacman -Sy --noconfirm cmake ninja clang curl git

ENV CC=clang CXX=clang++

WORKDIR /src
COPY . .

RUN mkdir build && cd build && \
    cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=ON && \
    ninja

FROM public.ecr.aws/lambda/provided:al2023

COPY --from=builder /src/build/tests/resources/lambda-test-fun /var/task/bootstrap

RUN chmod +x /var/task/bootstrap

ENTRYPOINT ["/var/task/bootstrap"]
