name: Deploy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_CDK_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: infra
        run: npm ci

      - name: CDK deploy
        working-directory: infra
        env:
          AWS_CODEBUILD_RELEASE_ROLE_ARN: ${{ secrets.AWS_CODEBUILD_RELEASE_ROLE_ARN }}
        run: npx cdk deploy --all --require-approval never
