name: Deploy Infrastructure

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 1" # Every Monday at 4pm UTC

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          role-to-assume: ${{ secrets.AWS_CDK_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: infra
        run: npm ci

      - name: CDK deploy
        working-directory: infra
        env:
          AWS_CODEBUILD_RELEASE_ROLE_ARN: ${{ secrets.AWS_CODEBUILD_RELEASE_ROLE_ARN }}
        run: npx cdk deploy --all --require-approval never
